### ISSUE TITLE
Power to spectrometers to be switchable

### ISSUE THREAD

**Issue by mhagdorn** [TeamPiccolo/piccolo3-server#2]
Power to spectrometers to be switchable. Richard has developed a controllable 5v switch for QEP spectros. Power will normally be on (switch closed) but should be able to schedule off/on to shutdown power when system asleep/not in use and power back up say 5 minutes before a measurement schedule starts.

**Comment by mhagdorn** [comment]
I am making some progress here. Do you want to be able to power on/off individual spectrometers or all of them at once?

**Comment by amacarth** [comment]
We will need to be able to power up each TEC spectrometer individually and there could be 3 cooled spectrometer. They will need to come on in a sequence each separated by say 10sec or similar so that the startup current peak is not all drawn at the same time. However, we only have one switch board just now.
